`Development`: Conditional Build Matrix
ls1intum/Artemis-Local-Setup-Docker pull request #3
Opened 2022-04-20 18:54 UTC by hhontheim

2022-05-01 15:45 UTC, hhontheim commented
**A hint regarding testing**: Since the images built in PRs are not released (by design), it's best to fork this repository and merge the feature branch into `main` there. This way, you'll have your own images to create containers from.

2022-05-15 08:10 UTC, sleiss reviewed
The changes look fine to me, I would however prefer if you could also document how one can build an image locally:
Previously, it was enough to just execute `docker build` for the desired Dockerfile, but now this fails since `VERSION` is no longer defined.

I think mentioning the use of `docker build .  --build-arg VERSION=...` should be sufficient for now, what do you think?

2022-05-15 08:27 UTC, sleiss commented
Another question regarding the caching: You mentioned the issues with the evicted cache entries due to the time limitation as well as the space limitation.

Have you thought about inlining the cache into the Docker image (see [e.g. here](https://github.com/docker/build-push-action/blob/c5e6528d5ddefc82f682165021e05edf58044bce/docs/advanced/cache.md#inline-cache))?
You would then have to pull the (old version of the) image from the registry before building, but maybe this can solve the caching limitation?

2022-05-26 12:23 UTC, Mtze requested changes
This is quite a dramatic change - I'm not sure if the introduced complexity by just building the images that changed is really necessary though. 
The atlassian versions change 2-4 times a year - and if they change, we update all the versions at once. So we have a minimal overhead there. I'm not sure how often the gitlab and jenkins images are update (cc @sleiss) that you add in the other PR. 

In any case - You have to improve the documentation for the new process. Please include at least: 
- How to add new Images to the build process 
- How to build the images locally 
- How the build matrix generation is working

I really appreciate the amount of thought you put in this PR!

2022-05-26 12:23 UTC, Mtze commented on jira/RELEASE
> +JIRA_VERSION=8.20.6
I guess this should be `VERSION` as well?

2022-05-26 12:23 UTC, Mtze commented on bitbucket/RELEASE
> +BITBUCKET_VERSION=7.21.0
Same as for jira

2022-05-26 12:23 UTC, Mtze commented on bamboo/RELEASE
> +BAMBOO_VERSION=8.1.3
Same as for jira

2022-05-26 12:23 UTC, Mtze commented on generate_build_matrix.sh
> +#!/bin/bash
Please add some comments/documentation to this file. I think it is not immediately obvious what the steps in this file do.

2022-05-26 12:23 UTC, Mtze commented on .github/workflows/build.yml
> +          tags: ghcr.io/${{ github.event.repository.owner.login }}/artemis-${{ matrix.name }}:latest,ghcr.io/${{ github.event.repository.owner.login }}/artemis-${{ matrix.name }}:${{ matrix.version }
```suggestion
          tags: 
            - ghcr.io/${{ github.event.repository.owner.login }}/artemis-${{ matrix.name }}:latest
            - ghcr.io/${{ github.event.repository.owner.login }}/artemis-${{ matrix.name }}:${{ matrix.version }}
```

2022-05-26 12:23 UTC, Mtze commented on .github/workflows/build.yml
> +          tags: ghcr.io/${{ github.event.repository.owner.login }}/artemis-bamboo:latest-${{ matrix.name }},ghcr.io/${{ github.event.repository.owner.login }}/artemis-bamboo:${{ matrix.version }}-${{
```suggestion
          tags: 
            - ghcr.io/${{ github.event.repository.owner.login }}/artemis-bamboo:latest-${{ matrix.name }}
            - ghcr.io/${{ github.event.repository.owner.login }}/artemis-bamboo:${{ matrix.version }}-${{ matrix.name }}
```

2023-11-27 12:16 UTC, closed without merging